# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QfKWolke6iSjr3h44gy5SArCTXbDQNs
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import PyPDF2
# import requests
# from fpdf import FPDF
# from io import BytesIO
# 
# # Função para extrair texto de um arquivo PDF
# def extrair_texto_pdf(arquivo_pdf):
#     leitor_pdf = PyPDF2.PdfReader(arquivo_pdf)
#     texto = ""
#     for pagina in leitor_pdf.pages:
#         texto += pagina.extract_text() or ""
#     return texto.strip()
# 
# # Função para buscar artigos na API da CrossRef
# def buscar_referencias_crossref(texto):
#     query = "+".join(texto.split()[:10])
#     url = f"https://api.crossref.org/works?query={query}&rows=10"
# 
#     try:
#         response = requests.get(url)
#         response.raise_for_status()
#         data = response.json()
#     except requests.exceptions.RequestException as e:
#         st.error(f"Erro ao acessar a API da CrossRef: {e}")
#         return []
# 
#     referencias = []
#     for item in data.get("message", {}).get("items", []):
#         titulo = item.get("title", ["Título não disponível"])[0]
#         link = item.get("URL", "Link não disponível")
#         referencias.append((titulo, link))
# 
#     return referencias
# 
# # Interface do Streamlit
# st.title("Verificador de Plágio - IN NICE")
# 
# arquivo_pdf = st.file_uploader("Faça upload de um arquivo PDF", type=["pdf"])
# 
# if st.button("Processar PDF"):
#     if arquivo_pdf is not None:
#         texto_usuario = extrair_texto_pdf(arquivo_pdf)
#         referencias = buscar_referencias_crossref(texto_usuario)
# 
#         if referencias:
#             st.subheader("Top 5 Referências encontradas:")
#             for i, (titulo, link) in enumerate(referencias[:5], 1):
#                 st.markdown(f"**{i}.** [{titulo}]({link})")
#         else:
#             st.warning("Nenhuma referência encontrada.")
#     else:
#         st.error("Por favor, carregue um arquivo PDF.")
#